### ISSUE TITLE
Recieved empty map_object response

### ISSUE THREAD

**Issue by mopschond** [PokeHunterProject/pogom-updated#4]
## Checklist
 - [X ] I have read the [FAQ](https://github.com/favll/pogom/blob/master/README.md#faq)
 - [X ] I have checked if this issue already exists (both open and closed issues)
 - [X ] I am using the most recent version of pogom from the master branch
 - [X ] If this is an installation issue, I am posting my OS, OS version, python version, pip version
 - [X ] I'm posting the complete log
 - [X ] I'm using a descriptive title for this issue

## My Issue

When I'm starting pogom with following cmd: "python runserver.py -H "0.0.0.0" -P 5000 -k "hashkey" its starting logging in top the account. But then it sends me this error over and over oder again:
Recieved empty map_object response. Logging out and retrying. I am trying this since 2 Days

**Comment by mopschond** [comment]
http://imgur.com/a/tQDZ6

**Comment by Paralysing** [comment]
"Fast pokemon go map, depreciated. (API 0.53 Beta Integration)". I would suggest trying to setup RocketMap (https://github.com/rocketmap/rocketmap), as this map is no longer updated.
